<html>
<head>
<script type="text/javascript"
	src="/js/jquery-1.5.1.min.js"></script>
	<script type="text/javascript"
	src="/js/jquery-ui-1.8.13.custom.min.js"></script>
	<link rel="stylesheet"
	href="/js/jquery-ui-1.8.13.custom.css"
	type="text/css" media="all" />
</head>

<body>

	<form id="form" method="<?php echo $this->form->getMethod() ;?>" action="<?php echo $this->form->getAction();?>"  >
	
	<script type="text/javascript">
	var x ;
    x= $(document);
	x.ready(inicia);

	function inicia(){
     var x ;
     x = $('#boton');
     x.click(agrega);
	}
		function agrega(){
			//alert("paso");
			$.post("index/agregar",$('#form').serialize(),
		
					 function(json) {
					      if(json.status =="ok" ){
						    $('#error').html(json.body);
						  }else if (json.status=="error"){
							  $('#error').html(json.body);
					       }
					  });

		}
	</script>
	<script>
	$(function() {
		$( "button", "#controles" ).button();
		
	});
	</script>
	


<center>
<h1>Agregar  Un Bus </h1>
<br>
<div id="controles">
<table border="0">
	<tr>
		<td><?php
echo $this->form->getElement('nombre');
?></td>
	</tr>
	<tr>
		<td><?php
echo $this->form->getElement('placa');
?></td>
	</tr>
	<tr>
		<td><?php
echo $this->form->getElement('tipo');
?></td>
	</tr>
	<tr>
		<td><?php
echo $this->form->getElement('Agregar');
?></td>
	</tr>
</table>
</div>
<br>
<div id="error"></div>
</center>
</form>
</body>


</html>
