<html>
<head>
 <script type="text/javascript" src="/js/jquery-1.5.1.min.js"></script> 


<script type="text/javascript" src="/js/jquery-ui-1.8.13.custom.min.js"></script>
<script type="text/javascript" src="/js/jquery.dataTables.js"></script>
<link rel="stylesheet" href="/js/jquery-ui-1.8.13.custom.css"
	type="text/css" media="all" />
</head>
<body>

<script type="text/javascript" charset="utf-8"> 
	$(document).ready(function() {
		$('#tabla').dataTable();
	} );
</script> 
<center>



<table id="tabla" border="1">
	<thead>
	<tr>
		<th>id</th>
		<th>Nombre bus</th>
		<th>Placa</th>
		<th>Tipo</th>
	</tr>
	</thead>
	<tbody>
	<?php foreach($this->buses as $buses) : ?> 
	<tr>	
		<td><?php echo htmlentities($this->escape($buses->id));?></td>
		<td><?php echo htmlentities($this->escape($buses->nombre));?></td>
		<td><?php echo htmlentities($this->escape($buses->placa));?></td>
		<td><?php echo htmlentities($this->escape($buses->tipo));?></td>
	</tr>
	<?php endforeach ; ?>
	</tbody>     					     
</table>
</center>

</body>



</html>