
<html>
<head>
<script type="text/javascript" src="/js/jquery-1.5.1.min.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.13.custom.min.js"></script>
<script type="text/javascript" src="/js/jquery.dataTables.js"></script>
<script type="text/javascript" src="/js/jquery.livequery.js"></script>
<link rel="stylesheet" href="/js/jquery-ui-1.8.13.custom.css"
	type="text/css" media="all" />
</head>

<body>
<script type="text/javascript">


$(document).ready(function() {
	$('.dataTables_filter').livequery(function(){
		  $('input').attr("id","buscar");		    
			  });			    

	setInterval(function(){
		if($('#buscar').val() == "" ){
			//	alert("vacio");
				var tabla =	$('#tabla').dataTable( {  
					"bProcessing": true,		    
					"sAjaxSource": "index/databuses",
					"bDestroy": true,
					"sScrollY": 300,
					"bJQueryUI": true,
					"sPaginationType": "full_numbers",		
					"aoColumns":[
						  			{ "id": "id" },
						  			{ "nombre": "nombre" },
						  			{ "placa": "placa" },
						  			{ "tipo": "tipo" }		  			
							  		],
						
				   "fnRowCallback": function( nRow, aaData, iDisplayIndex ) {  
			         //   aData:"index/databuses";
						return nRow;			
					}
				   });
			}else{
			//	alert("no vacio");
				clearInterval(tabla);
				}
  	 }, 10000);

	var tabla =	$('#tabla').dataTable( {  
		"bProcessing": true,		    
		"sAjaxSource": "index/databuses",
		"bDestroy": true,
		"sScrollY": 300,
		"bJQueryUI": true,
		"sPaginationType": "full_numbers",		
		"aoColumns":[
			  			{ "id": "id" },
			  			{ "nombre": "nombre" },
			  			{ "placa": "placa" },
			  			{ "tipo": "tipo" }		  			
				  		],
			
	   "fnRowCallback": function( nRow, aaData, iDisplayIndex ) {  
         //   aData:"index/databuses";
			return nRow;			
		}
	   });
});

/*$(document).ready(function() {
	$('.dataTables_filter').livequery(function(){
		  $('input').attr("id","buscar");		    
			  });			    


	 var tabla =$('#tabla').dataTable( {  
		"bProcessing": true,		    
		"sAjaxSource": "index/databuses",
		"bDestroy": true,
		"fnClearTable": true ,
		"sScrollY": 300,
		"bJQueryUI": true,
		"fnDraw":true,
		"sPaginationType": "full_numbers",		
		"aoColumns":[
			  			{ "id": "id" },
			  			{ "nombre": "nombre" },
			  			{ "placa": "placa" },
			  			{ "tipo": "tipo" }		  			
				  		],
			
	   "fnRowCallback": function( nRow, aaData, iDisplayIndex ) {  
         //   aData:"index/databuses";
			return nRow;			
		}
	   });
	  
	   

	
	setInterval(function(){
		if($('#buscar').val() == "" ){
			//	alert("vacio");
				if (typeof tabla == 'undefined') {
					
					tabla =  $('#tabla').dataTable({
						"bProcessing": true,		    
						"sAjaxSource": "index/databuses",
						"bDestroy": true,
						"fnClearTable": true ,
						"sScrollY": 300,
						"bJQueryUI": true,
						"sPaginationType": "full_numbers",		
						"aoColumns":[
			  						{ "id": "id" },
			  						{ "nombre": "nombre" },
			  						{ "placa": "placa" },
			  						{ "tipo": "tipo" }		  			
				  		],		
	   				"fnRowCallback": function( nRow, aaData, iDisplayIndex ) {  
     				    //   aData:"index/databuses";
						return nRow;			
						}
						});
					}
				else
				{
				    //alert("entro a  recargas");
					tabla.fnClearTable(o);
					tabla.fnDraw();
				}
			}else{
			//	alert("no vacio");
				clearInterval(tabla);
				}
  	 }, 10000);

	
});*/

/*$(document).ready(function() {
	$('.dataTables_filter').livequery(function(){
		  $('input').attr("id","buscar");		    
			  });			    

	var tabla =	$('#tabla').dataTable( {  
		"bProcessing": true,		    
		"sAjaxSource": "index/databuses",
		"bDestroy": true,
		"fnClearTable": null ,
		"sScrollY": 300,
		"bJQueryUI": true,
		"sPaginationType": "full_numbers",		
		"aoColumns":[
			  			{ "id": "id" },
			  			{ "nombre": "nombre" },
			  			{ "placa": "placa" },
			  			{ "tipo": "tipo" }		  			
				  		],
			
	   "fnRowCallback": function( nRow, aaData, iDisplayIndex ) {  
         //   aData:"index/databuses";
			return nRow;			
		}
	   });
	
	setInterval(function(){
		if($('#buscar').val() == "" ){
			tabla.fnClearTable(0);
			
			tabla.fnDraw();
			
			}else{
			//	alert("no vacio");
				clearInterval(tabla);
				}
  	 }, 10000);

	
});*/

</script>
<center>

<table id="tabla" width="200">
	<thead>
		<tr>
			<th>id</th>
			<th>nombre</th>
			<th>placa</th>
			<th>tipo</th>
		</tr>
	</thead>
</table>
</br>
<!-- <iframe id="basicEmbed" src="https://api.opentok.com/hl/embed/2emb22c9644884fc9b075c64a0213b736c587cd1" width="350" height="265" style="border:none"></iframe> -->

</center>
</body>


</html>
